#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════
//  ZytekOS — License Key Generator CLI
//  Uso: node scripts/generate-license.js
//       node scripts/generate-license.js REST pro 2027-12-31
// ═══════════════════════════════════════════════════════════════
const args    = process.argv.slice(2)
const tenant  = (args[0] || 'CUST').toUpperCase().slice(0,4).padEnd(4,'X')
const plan    = (args[1] || 'pro').toUpperCase().slice(0,4).padEnd(4,'0')
const year    = new Date().getFullYear()
const expires = args[2] || `${year + 1}-12-31`
const key     = `ZYTEK-${tenant}-${plan}-${year}`

console.log('\n╔══════════════════════════════════════════╗')
console.log('║  ZytekOS License Key Generator          ║')
console.log('╚══════════════════════════════════════════╝\n')
console.log(`  Key:      ${key}`)
console.log(`  Tenant:   ${tenant}`)
console.log(`  Plan:     ${plan.toLowerCase()}`)
console.log(`  Expires:  ${expires}`)
console.log(`\n  SQL para insertar en Supabase:`)
console.log(`  ─────────────────────────────`)
console.log(`  INSERT INTO zytek_licenses (key, tenant_id, tenant_name, plan, expires_at)`)
console.log(`  VALUES ('${key}', '<tenant_uuid>', '<Nombre del Cliente>', '${plan.toLowerCase()}', '${expires}');`)
console.log()

// También crear el script SQL listo para copiar
const fs   = require('fs')
const sql  = `-- Generated by ZytekOS License Generator\nINSERT INTO zytek_licenses (key, tenant_id, tenant_name, plan, modules, max_users, expires_at, active)\nVALUES (\n  '${key}',\n  '<TENANT_UUID>',\n  '<NOMBRE_CLIENTE>',\n  '${plan.toLowerCase()}',\n  ARRAY['*'],\n  10,\n  '${expires}',\n  true\n);\n`
const fname = `license_${key.replace(/\-/g,'_').toLowerCase()}.sql`
fs.writeFileSync(fname, sql)
console.log(`  SQL guardado en: ${fname}\n`)
